#!/bin/bash


FILES=$(ls -A /etc/squid)


if [ "$FILES" = "" ];then

	cp -rf /opt/squid/* /etc/squid/

fi

#Permisos 
chown -R proxy.proxy /etc/squid
chown -R proxy.proxy /var/log/squid
chown -R proxy.proxy /var/spool/squid




exec /usr/sbin/squid -N -d 11


